# Generated by Django 4.0.9 on 2023-03-28 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('attendance_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Naam bijeenkomst')),
                ('join_code', models.CharField(default='', help_text='Verzin een code die studenten kunnen gebruiken om toegang tot de les te krijgen.', max_length=200, verbose_name='Toegangscode')),
                ('active', models.BooleanField(default=True, verbose_name='Actief')),
                ('start_date', models.DateTimeField(null=True, verbose_name='Begint')),
                ('end_date', models.DateTimeField(null=True, verbose_name='Eindigt')),
            ],
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('classe_id', models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='Klas')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(max_length=150, primary_key=True, serialize=False, verbose_name='Cursuscode')),
                ('course_name', models.CharField(max_length=150, verbose_name='Cursusnaam')),
                ('elective', models.BooleanField(null=True, verbose_name='Keuzevak')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Studentnummer')),
                ('email', models.EmailField(max_length=250, verbose_name='E-mailadres')),
                ('last_name', models.CharField(max_length=150, verbose_name='Achternaam')),
                ('first_name', models.CharField(max_length=150, verbose_name='Voornaam')),
                ('project_group', models.CharField(max_length=255, verbose_name='Projectgroep')),
                ('classe', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='attendanceItems.classe', verbose_name='Klas')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.AutoField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=150, verbose_name='Achternaam')),
                ('first_name', models.CharField(max_length=150, verbose_name='Voornaam')),
                ('email', models.EmailField(max_length=250, verbose_name='E-mailadres')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherSchedule',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(null=True, verbose_name='Datum')),
                ('classroom', models.CharField(max_length=150, verbose_name='Leslocatie')),
                ('classe', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='attendanceItems.classe', verbose_name='Klas')),
                ('course', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='attendanceItems.course', verbose_name='Cursusnaam')),
                ('teacher', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='attendanceItems.teacher', verbose_name='Docent')),
            ],
        ),
        migrations.CreateModel(
            name='StudentSchedule',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(null=True, verbose_name='Datum')),
                ('classroom', models.CharField(max_length=150, verbose_name='Leslocatie')),
                ('course', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='attendanceItems.course', verbose_name='Cursusnaam')),
                ('student', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='attendanceItems.student', verbose_name='Studentnummer')),
                ('teacher', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='attendanceItems.teacher', verbose_name='Docent')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendanceItems.attendance', verbose_name='Bijeenkomst')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendanceItems.student', verbose_name='Studentnummer')),
            ],
        ),
        migrations.AddField(
            model_name='classe',
            name='teacher',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='attendanceItems.teacher', verbose_name="SLC'er"),
        ),
        migrations.AddField(
            model_name='attendance',
            name='classe',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='attendanceItems.classe', verbose_name='Klas'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='course',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='attendanceItems.course', verbose_name='Cursusnaam'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='teacher',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='attendanceItems.teacher', verbose_name='Docent'),
        ),
    ]
