# Generated by Django 4.0 on 2023-03-28 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceItems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='is_present',
            field=models.BooleanField(default=False, verbose_name='Aanwezig'),
        ),
    ]
