# Generated by Django 4.0.9 on 2023-04-05 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceItems', '0002_history_date_joined_history_is_present'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='date_joined',
            field=models.DateTimeField(default='', null=True, verbose_name='Datum aangemeld'),
        ),
        migrations.CreateModel(
            name='Present',
            fields=[
                ('present_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_joined', models.DateTimeField(default='', null=True, verbose_name='Datum aangemeld')),
                ('is_present', models.BooleanField(default=False, verbose_name='Aanwezig')),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendanceItems.attendance', verbose_name='Bijeenkomst')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendanceItems.student', verbose_name='Studentnummer')),
            ],
        ),
    ]
